#配置数据库连接信息
spring:
  application:
    name: spring-framework


  datasource:
    url: jdbc:mysql://localhost:3306/blog-0901
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 101626

  redis:
    host: localhost
    port: 6379
    password:
    database: 0

# 测试使用,配置product
product:
  ready: true
  open-hours: 8:30-22:00